// @ts-nocheck
// Generated Code, do not edit manually
import * as Cesium from "cesium";

export type MappingExported = {
  animation: Cesium.Animation;
  animationViewModel: Cesium.AnimationViewModel;
  appearance: Cesium.Appearance;
  approximateTerrainHeights: Cesium.ApproximateTerrainHeights;
  arcGisTiledElevationTerrainProvider: Cesium.ArcGISTiledElevationTerrainProvider;
  arcGisMapServerImageryProvider: Cesium.ArcGisMapServerImageryProvider;
  arcType: Cesium.ArcType;
  associativeArray: Cesium.AssociativeArray;
  attributeCompression: Cesium.AttributeCompression;
  attributeType: Cesium.AttributeType;
  autoExposure: Cesium.AutoExposure;
  autolinker: Cesium.Autolinker;
  automaticUniforms: Cesium.AutomaticUniforms;
  axis: Cesium.Axis;
  axisAlignedBoundingBox: Cesium.AxisAlignedBoundingBox;
  baseLayerPicker: Cesium.BaseLayerPicker;
  baseLayerPickerViewModel: Cesium.BaseLayerPickerViewModel;
  batchTable: Cesium.BatchTable;
  batched3DModel3DTileContent: Cesium.Batched3DModel3DTileContent;
  billboard: Cesium.Billboard;
  billboardCollection: Cesium.BillboardCollection;
  billboardGraphics: Cesium.BillboardGraphics;
  billboardVisualizer: Cesium.BillboardVisualizer;
  bingMapsApi: Cesium.BingMapsApi;
  bingMapsGeocoderService: Cesium.BingMapsGeocoderService;
  bingMapsImageryProvider: Cesium.BingMapsImageryProvider;
  bingMapsStyle: Cesium.BingMapsStyle;
  blendEquation: Cesium.BlendEquation;
  blendFunction: Cesium.BlendFunction;
  blendOption: Cesium.BlendOption;
  blendingState: Cesium.BlendingState;
  boundingRectangle: Cesium.BoundingRectangle;
  boundingSphere: Cesium.BoundingSphere;
  boundingSphereState: Cesium.BoundingSphereState;
  boxEmitter: Cesium.BoxEmitter;
  boxGeometry: Cesium.BoxGeometry;
  boxGeometryUpdater: Cesium.BoxGeometryUpdater;
  boxGraphics: Cesium.BoxGraphics;
  boxOutlineGeometry: Cesium.BoxOutlineGeometry;
  brdfLutGenerator: Cesium.BrdfLutGenerator;
  buffer: Cesium.Buffer;
  bufferUsage: Cesium.BufferUsage;
  callbackProperty: Cesium.CallbackProperty;
  camera: Cesium.Camera;
  cameraEventAggregator: Cesium.CameraEventAggregator;
  cameraEventType: Cesium.CameraEventType;
  cameraFlightPath: Cesium.CameraFlightPath;
  cartesian2: Cesium.Cartesian2;
  cartesian3: Cesium.Cartesian3;
  cartesian4: Cesium.Cartesian4;
  cartographic: Cesium.Cartographic;
  cartographicGeocoderService: Cesium.CartographicGeocoderService;
  catmullRomSpline: Cesium.CatmullRomSpline;
  cesium3DTile: Cesium.Cesium3DTile;
  cesium3DTileBatchTable: Cesium.Cesium3DTileBatchTable;
  cesium3DTileColorBlendMode: Cesium.Cesium3DTileColorBlendMode;
  cesium3DTileContent: Cesium.Cesium3DTileContent;
  cesium3DTileContentFactory: Cesium.Cesium3DTileContentFactory;
  cesium3DTileContentState: Cesium.Cesium3DTileContentState;
  cesium3DTileFeature: Cesium.Cesium3DTileFeature;
  cesium3DTileFeatureTable: Cesium.Cesium3DTileFeatureTable;
  cesium3DTileOptimizationHint: Cesium.Cesium3DTileOptimizationHint;
  cesium3DTileOptimizations: Cesium.Cesium3DTileOptimizations;
  cesium3DTilePass: Cesium.Cesium3DTilePass;
  cesium3DTilePassState: Cesium.Cesium3DTilePassState;
  cesium3DTilePointFeature: Cesium.Cesium3DTilePointFeature;
  cesium3DTileRefine: Cesium.Cesium3DTileRefine;
  cesium3DTileStyle: Cesium.Cesium3DTileStyle;
  cesium3DTileStyleEngine: Cesium.Cesium3DTileStyleEngine;
  cesium3DTilesInspector: Cesium.Cesium3DTilesInspector;
  cesium3DTilesInspectorViewModel: Cesium.Cesium3DTilesInspectorViewModel;
  cesium3DTileset: Cesium.Cesium3DTileset;
  cesium3DTilesetCache: Cesium.Cesium3DTilesetCache;
  cesium3DTilesetGraphics: Cesium.Cesium3DTilesetGraphics;
  cesium3DTilesetHeatmap: Cesium.Cesium3DTilesetHeatmap;
  cesium3DTilesetMostDetailedTraversal: Cesium.Cesium3DTilesetMostDetailedTraversal;
  cesium3DTilesetStatistics: Cesium.Cesium3DTilesetStatistics;
  cesium3DTilesetTraversal: Cesium.Cesium3DTilesetTraversal;
  cesium3DTilesetVisualizer: Cesium.Cesium3DTilesetVisualizer;
  cesiumInspector: Cesium.CesiumInspector;
  cesiumInspectorViewModel: Cesium.CesiumInspectorViewModel;
  cesiumTerrainProvider: Cesium.CesiumTerrainProvider;
  cesiumWidget: Cesium.CesiumWidget;
  check: Cesium.Check;
  checkerboardMaterialProperty: Cesium.CheckerboardMaterialProperty;
  circleEmitter: Cesium.CircleEmitter;
  circleGeometry: Cesium.CircleGeometry;
  circleOutlineGeometry: Cesium.CircleOutlineGeometry;
  classificationModel: Cesium.ClassificationModel;
  classificationPrimitive: Cesium.ClassificationPrimitive;
  classificationType: Cesium.ClassificationType;
  clearCommand: Cesium.ClearCommand;
  clippingPlane: Cesium.ClippingPlane;
  clippingPlaneCollection: Cesium.ClippingPlaneCollection;
  clock: Cesium.Clock;
  clockRange: Cesium.ClockRange;
  clockStep: Cesium.ClockStep;
  clockViewModel: Cesium.ClockViewModel;
  color: Cesium.Color;
  colorBlendMode: Cesium.ColorBlendMode;
  colorGeometryInstanceAttribute: Cesium.ColorGeometryInstanceAttribute;
  colorMaterialProperty: Cesium.ColorMaterialProperty;
  command: Cesium.Command;
  componentDatatype: Cesium.ComponentDatatype;
  composite3DTileContent: Cesium.Composite3DTileContent;
  compositeEntityCollection: Cesium.CompositeEntityCollection;
  compositeMaterialProperty: Cesium.CompositeMaterialProperty;
  compositePositionProperty: Cesium.CompositePositionProperty;
  compositeProperty: Cesium.CompositeProperty;
  compressedTextureBuffer: Cesium.CompressedTextureBuffer;
  computeCommand: Cesium.ComputeCommand;
  computeEngine: Cesium.ComputeEngine;
  conditionsExpression: Cesium.ConditionsExpression;
  coneEmitter: Cesium.ConeEmitter;
  constantPositionProperty: Cesium.ConstantPositionProperty;
  constantProperty: Cesium.ConstantProperty;
  context: Cesium.Context;
  contextLimits: Cesium.ContextLimits;
  coplanarPolygonGeometry: Cesium.CoplanarPolygonGeometry;
  coplanarPolygonGeometryLibrary: Cesium.CoplanarPolygonGeometryLibrary;
  coplanarPolygonOutlineGeometry: Cesium.CoplanarPolygonOutlineGeometry;
  cornerType: Cesium.CornerType;
  corridorGeometry: Cesium.CorridorGeometry;
  corridorGeometryLibrary: Cesium.CorridorGeometryLibrary;
  corridorGeometryUpdater: Cesium.CorridorGeometryUpdater;
  corridorGraphics: Cesium.CorridorGraphics;
  corridorOutlineGeometry: Cesium.CorridorOutlineGeometry;
  credit: Cesium.Credit;
  creditDisplay: Cesium.CreditDisplay;
  cubeMap: Cesium.CubeMap;
  cubeMapFace: Cesium.CubeMapFace;
  cubicRealPolynomial: Cesium.CubicRealPolynomial;
  cullFace: Cesium.CullFace;
  cullingVolume: Cesium.CullingVolume;
  customDataSource: Cesium.CustomDataSource;
  cylinderGeometry: Cesium.CylinderGeometry;
  cylinderGeometryLibrary: Cesium.CylinderGeometryLibrary;
  cylinderGeometryUpdater: Cesium.CylinderGeometryUpdater;
  cylinderGraphics: Cesium.CylinderGraphics;
  cylinderOutlineGeometry: Cesium.CylinderOutlineGeometry;
  czmlDataSource: Cesium.CzmlDataSource;
  dataSource: Cesium.DataSource;
  dataSourceClock: Cesium.DataSourceClock;
  dataSourceCollection: Cesium.DataSourceCollection;
  dataSourceDisplay: Cesium.DataSourceDisplay;
  debugAppearance: Cesium.DebugAppearance;
  debugCameraPrimitive: Cesium.DebugCameraPrimitive;
  debugModelMatrixPrimitive: Cesium.DebugModelMatrixPrimitive;
  defaultProxy: Cesium.DefaultProxy;
  depthFunction: Cesium.DepthFunction;
  depthPlane: Cesium.DepthPlane;
  derivedCommand: Cesium.DerivedCommand;
  developerError: Cesium.DeveloperError;
  deviceOrientationCameraController: Cesium.DeviceOrientationCameraController;
  directionalLight: Cesium.DirectionalLight;
  discardEmptyTileImagePolicy: Cesium.DiscardEmptyTileImagePolicy;
  discardMissingTileImagePolicy: Cesium.DiscardMissingTileImagePolicy;
  distanceDisplayCondition: Cesium.DistanceDisplayCondition;
  distanceDisplayConditionGeometryInstanceAttribute: Cesium.DistanceDisplayConditionGeometryInstanceAttribute;
  doublyLinkedList: Cesium.DoublyLinkedList;
  dracoLoader: Cesium.DracoLoader;
  drawCommand: Cesium.DrawCommand;
  dynamicGeometryBatch: Cesium.DynamicGeometryBatch;
  dynamicGeometryUpdater: Cesium.DynamicGeometryUpdater;
  earthOrientationParameters: Cesium.EarthOrientationParameters;
  earthOrientationParametersSample: Cesium.EarthOrientationParametersSample;
  easingFunction: Cesium.EasingFunction;
  ellipseGeometry: Cesium.EllipseGeometry;
  ellipseGeometryLibrary: Cesium.EllipseGeometryLibrary;
  ellipseGeometryUpdater: Cesium.EllipseGeometryUpdater;
  ellipseGraphics: Cesium.EllipseGraphics;
  ellipseOutlineGeometry: Cesium.EllipseOutlineGeometry;
  ellipsoid: Cesium.Ellipsoid;
  ellipsoidGeodesic: Cesium.EllipsoidGeodesic;
  ellipsoidGeometry: Cesium.EllipsoidGeometry;
  ellipsoidGeometryUpdater: Cesium.EllipsoidGeometryUpdater;
  ellipsoidGraphics: Cesium.EllipsoidGraphics;
  ellipsoidOutlineGeometry: Cesium.EllipsoidOutlineGeometry;
  ellipsoidPrimitive: Cesium.EllipsoidPrimitive;
  ellipsoidRhumbLine: Cesium.EllipsoidRhumbLine;
  ellipsoidSurfaceAppearance: Cesium.EllipsoidSurfaceAppearance;
  ellipsoidTangentPlane: Cesium.EllipsoidTangentPlane;
  ellipsoidTerrainProvider: Cesium.EllipsoidTerrainProvider;
  ellipsoidalOccluder: Cesium.EllipsoidalOccluder;
  empty3DTileContent: Cesium.Empty3DTileContent;
  encodedCartesian3: Cesium.EncodedCartesian3;
  entity: Cesium.Entity;
  entityCluster: Cesium.EntityCluster;
  entityCollection: Cesium.EntityCollection;
  entityView: Cesium.EntityView;
  event: Cesium.Event;
  eventHelper: Cesium.EventHelper;
  expression: Cesium.Expression;
  expressionNodeType: Cesium.ExpressionNodeType;
  extrapolationType: Cesium.ExtrapolationType;
  fxaa311: Cesium.FXAA3_11;
  featureDetection: Cesium.FeatureDetection;
  fog: Cesium.Fog;
  forEach: Cesium.ForEach;
  frameRateMonitor: Cesium.FrameRateMonitor;
  frameState: Cesium.FrameState;
  framebuffer: Cesium.Framebuffer;
  frustumCommands: Cesium.FrustumCommands;
  frustumGeometry: Cesium.FrustumGeometry;
  frustumOutlineGeometry: Cesium.FrustumOutlineGeometry;
  fullscreen: Cesium.Fullscreen;
  fullscreenButton: Cesium.FullscreenButton;
  fullscreenButtonViewModel: Cesium.FullscreenButtonViewModel;
  geoJsonDataSource: Cesium.GeoJsonDataSource;
  geocodeType: Cesium.GeocodeType;
  geocoder: Cesium.Geocoder;
  geocoderService: Cesium.GeocoderService;
  geocoderViewModel: Cesium.GeocoderViewModel;
  geographicProjection: Cesium.GeographicProjection;
  geographicTilingScheme: Cesium.GeographicTilingScheme;
  geometry: Cesium.Geometry;
  geometry3DTileContent: Cesium.Geometry3DTileContent;
  geometryAttribute: Cesium.GeometryAttribute;
  geometryAttributes: Cesium.GeometryAttributes;
  geometryInstance: Cesium.GeometryInstance;
  geometryInstanceAttribute: Cesium.GeometryInstanceAttribute;
  geometryOffsetAttribute: Cesium.GeometryOffsetAttribute;
  geometryPipeline: Cesium.GeometryPipeline;
  geometryType: Cesium.GeometryType;
  geometryUpdater: Cesium.GeometryUpdater;
  geometryVisualizer: Cesium.GeometryVisualizer;
  getFeatureInfoFormat: Cesium.GetFeatureInfoFormat;
  globe: Cesium.Globe;
  globeDepth: Cesium.GlobeDepth;
  globeSurfaceShaderSet: Cesium.GlobeSurfaceShaderSet;
  globeSurfaceTile: Cesium.GlobeSurfaceTile;
  globeSurfaceTileProvider: Cesium.GlobeSurfaceTileProvider;
  globeTranslucency: Cesium.GlobeTranslucency;
  globeTranslucencyFramebuffer: Cesium.GlobeTranslucencyFramebuffer;
  globeTranslucencyState: Cesium.GlobeTranslucencyState;
  googleEarthEnterpriseImageryProvider: Cesium.GoogleEarthEnterpriseImageryProvider;
  googleEarthEnterpriseMapsProvider: Cesium.GoogleEarthEnterpriseMapsProvider;
  googleEarthEnterpriseMetadata: Cesium.GoogleEarthEnterpriseMetadata;
  googleEarthEnterpriseTerrainData: Cesium.GoogleEarthEnterpriseTerrainData;
  googleEarthEnterpriseTerrainProvider: Cesium.GoogleEarthEnterpriseTerrainProvider;
  googleEarthEnterpriseTileInformation: Cesium.GoogleEarthEnterpriseTileInformation;
  gregorianDate: Cesium.GregorianDate;
  gridImageryProvider: Cesium.GridImageryProvider;
  gridMaterialProperty: Cesium.GridMaterialProperty;
  groundGeometryUpdater: Cesium.GroundGeometryUpdater;
  groundPolylineGeometry: Cesium.GroundPolylineGeometry;
  groundPolylinePrimitive: Cesium.GroundPolylinePrimitive;
  groundPrimitive: Cesium.GroundPrimitive;
  headingPitchRange: Cesium.HeadingPitchRange;
  headingPitchRoll: Cesium.HeadingPitchRoll;
  heap: Cesium.Heap;
  heightReference: Cesium.HeightReference;
  heightmapEncoding: Cesium.HeightmapEncoding;
  heightmapTerrainData: Cesium.HeightmapTerrainData;
  heightmapTessellator: Cesium.HeightmapTessellator;
  hermitePolynomialApproximation: Cesium.HermitePolynomialApproximation;
  hermiteSpline: Cesium.HermiteSpline;
  homeButton: Cesium.HomeButton;
  homeButtonViewModel: Cesium.HomeButtonViewModel;
  horizontalOrigin: Cesium.HorizontalOrigin;
  iau2000Orientation: Cesium.Iau2000Orientation;
  iau2006XysData: Cesium.Iau2006XysData;
  iau2006XysSample: Cesium.Iau2006XysSample;
  iauOrientationAxes: Cesium.IauOrientationAxes;
  iauOrientationParameters: Cesium.IauOrientationParameters;
  imageMaterialProperty: Cesium.ImageMaterialProperty;
  imagery: Cesium.Imagery;
  imageryLayer: Cesium.ImageryLayer;
  imageryLayerCollection: Cesium.ImageryLayerCollection;
  imageryLayerFeatureInfo: Cesium.ImageryLayerFeatureInfo;
  imageryProvider: Cesium.ImageryProvider;
  imagerySplitDirection: Cesium.ImagerySplitDirection;
  imageryState: Cesium.ImageryState;
  indexDatatype: Cesium.IndexDatatype;
  infoBox: Cesium.InfoBox;
  infoBoxViewModel: Cesium.InfoBoxViewModel;
  inspectorShared: Cesium.InspectorShared;
  instanced3DModel3DTileContent: Cesium.Instanced3DModel3DTileContent;
  interpolationAlgorithm: Cesium.InterpolationAlgorithm;
  intersect: Cesium.Intersect;
  intersectionTests: Cesium.IntersectionTests;
  intersections2D: Cesium.Intersections2D;
  interval: Cesium.Interval;
  invertClassification: Cesium.InvertClassification;
  ion: Cesium.Ion;
  ionGeocoderService: Cesium.IonGeocoderService;
  ionImageryProvider: Cesium.IonImageryProvider;
  ionResource: Cesium.IonResource;
  ionWorldImageryStyle: Cesium.IonWorldImageryStyle;
  iso8601: Cesium.Iso8601;
  jobScheduler: Cesium.JobScheduler;
  jobType: Cesium.JobType;
  julianDate: Cesium.JulianDate;
  keyboardEventModifier: Cesium.KeyboardEventModifier;
  kmlCamera: Cesium.KmlCamera;
  kmlDataSource: Cesium.KmlDataSource;
  kmlLookAt: Cesium.KmlLookAt;
  kmlTour: Cesium.KmlTour;
  kmlTourFlyTo: Cesium.KmlTourFlyTo;
  kmlTourWait: Cesium.KmlTourWait;
  label: Cesium.Label;
  labelCollection: Cesium.LabelCollection;
  labelGraphics: Cesium.LabelGraphics;
  labelStyle: Cesium.LabelStyle;
  labelVisualizer: Cesium.LabelVisualizer;
  lagrangePolynomialApproximation: Cesium.LagrangePolynomialApproximation;
  leapSecond: Cesium.LeapSecond;
  lercDecode: Cesium.LercDecode;
  light: Cesium.Light;
  linearApproximation: Cesium.LinearApproximation;
  linearSpline: Cesium.LinearSpline;
  managedArray: Cesium.ManagedArray;
  mapMode2D: Cesium.MapMode2D;
  mapProjection: Cesium.MapProjection;
  mapboxApi: Cesium.MapboxApi;
  mapboxImageryProvider: Cesium.MapboxImageryProvider;
  mapboxStyleImageryProvider: Cesium.MapboxStyleImageryProvider;
  material: Cesium.Material;
  materialAppearance: Cesium.MaterialAppearance;
  materialProperty: Cesium.MaterialProperty;
  math: Cesium.Math;
  matrix2: Cesium.Matrix2;
  matrix3: Cesium.Matrix3;
  matrix4: Cesium.Matrix4;
  mipmapHint: Cesium.MipmapHint;
  model: Cesium.Model;
  modelAnimation: Cesium.ModelAnimation;
  modelAnimationCache: Cesium.ModelAnimationCache;
  modelAnimationCollection: Cesium.ModelAnimationCollection;
  modelAnimationLoop: Cesium.ModelAnimationLoop;
  modelAnimationState: Cesium.ModelAnimationState;
  modelGraphics: Cesium.ModelGraphics;
  modelInstance: Cesium.ModelInstance;
  modelInstanceCollection: Cesium.ModelInstanceCollection;
  modelLoadResources: Cesium.ModelLoadResources;
  modelMaterial: Cesium.ModelMaterial;
  modelMesh: Cesium.ModelMesh;
  modelNode: Cesium.ModelNode;
  modelOutlineLoader: Cesium.ModelOutlineLoader;
  modelUtility: Cesium.ModelUtility;
  modelVisualizer: Cesium.ModelVisualizer;
  moon: Cesium.Moon;
  navigationHelpButton: Cesium.NavigationHelpButton;
  navigationHelpButtonViewModel: Cesium.NavigationHelpButtonViewModel;
  nearFarScalar: Cesium.NearFarScalar;
  neverTileDiscardPolicy: Cesium.NeverTileDiscardPolicy;
  noSleep: Cesium.NoSleep;
  nodeTransformationProperty: Cesium.NodeTransformationProperty;
  oit: Cesium.OIT;
  occluder: Cesium.Occluder;
  octahedralProjectedCubeMap: Cesium.OctahedralProjectedCubeMap;
  offsetGeometryInstanceAttribute: Cesium.OffsetGeometryInstanceAttribute;
  openCageGeocoderService: Cesium.OpenCageGeocoderService;
  openStreetMapImageryProvider: Cesium.OpenStreetMapImageryProvider;
  orderedGroundPrimitiveCollection: Cesium.OrderedGroundPrimitiveCollection;
  orientedBoundingBox: Cesium.OrientedBoundingBox;
  orthographicFrustum: Cesium.OrthographicFrustum;
  orthographicOffCenterFrustum: Cesium.OrthographicOffCenterFrustum;
  packable: Cesium.Packable;
  packableForInterpolation: Cesium.PackableForInterpolation;
  particle: Cesium.Particle;
  particleBurst: Cesium.ParticleBurst;
  particleEmitter: Cesium.ParticleEmitter;
  particleSystem: Cesium.ParticleSystem;
  pass: Cesium.Pass;
  passState: Cesium.PassState;
  pathGraphics: Cesium.PathGraphics;
  pathVisualizer: Cesium.PathVisualizer;
  peliasGeocoderService: Cesium.PeliasGeocoderService;
  perInstanceColorAppearance: Cesium.PerInstanceColorAppearance;
  performanceDisplay: Cesium.PerformanceDisplay;
  performanceWatchdog: Cesium.PerformanceWatchdog;
  performanceWatchdogViewModel: Cesium.PerformanceWatchdogViewModel;
  perspectiveFrustum: Cesium.PerspectiveFrustum;
  perspectiveOffCenterFrustum: Cesium.PerspectiveOffCenterFrustum;
  pickDepth: Cesium.PickDepth;
  pickDepthFramebuffer: Cesium.PickDepthFramebuffer;
  pickFramebuffer: Cesium.PickFramebuffer;
  picking: Cesium.Picking;
  pinBuilder: Cesium.PinBuilder;
  pixelDatatype: Cesium.PixelDatatype;
  pixelFormat: Cesium.PixelFormat;
  plane: Cesium.Plane;
  planeGeometry: Cesium.PlaneGeometry;
  planeGeometryUpdater: Cesium.PlaneGeometryUpdater;
  planeGraphics: Cesium.PlaneGraphics;
  planeOutlineGeometry: Cesium.PlaneOutlineGeometry;
  pointCloud: Cesium.PointCloud;
  pointCloud3DTileContent: Cesium.PointCloud3DTileContent;
  pointCloudEyeDomeLighting: Cesium.PointCloudEyeDomeLighting;
  pointCloudShading: Cesium.PointCloudShading;
  pointGraphics: Cesium.PointGraphics;
  pointPrimitive: Cesium.PointPrimitive;
  pointPrimitiveCollection: Cesium.PointPrimitiveCollection;
  pointVisualizer: Cesium.PointVisualizer;
  polygonGeometry: Cesium.PolygonGeometry;
  polygonGeometryLibrary: Cesium.PolygonGeometryLibrary;
  polygonGeometryUpdater: Cesium.PolygonGeometryUpdater;
  polygonGraphics: Cesium.PolygonGraphics;
  polygonHierarchy: Cesium.PolygonHierarchy;
  polygonOutlineGeometry: Cesium.PolygonOutlineGeometry;
  polygonPipeline: Cesium.PolygonPipeline;
  polyline: Cesium.Polyline;
  polylineArrowMaterialProperty: Cesium.PolylineArrowMaterialProperty;
  polylineCollection: Cesium.PolylineCollection;
  polylineColorAppearance: Cesium.PolylineColorAppearance;
  polylineDashMaterialProperty: Cesium.PolylineDashMaterialProperty;
  polylineGeometry: Cesium.PolylineGeometry;
  polylineGeometryUpdater: Cesium.PolylineGeometryUpdater;
  polylineGlowMaterialProperty: Cesium.PolylineGlowMaterialProperty;
  polylineGraphics: Cesium.PolylineGraphics;
  polylineMaterialAppearance: Cesium.PolylineMaterialAppearance;
  polylineOutlineMaterialProperty: Cesium.PolylineOutlineMaterialProperty;
  polylinePipeline: Cesium.PolylinePipeline;
  polylineVisualizer: Cesium.PolylineVisualizer;
  polylineVolumeGeometry: Cesium.PolylineVolumeGeometry;
  polylineVolumeGeometryLibrary: Cesium.PolylineVolumeGeometryLibrary;
  polylineVolumeGeometryUpdater: Cesium.PolylineVolumeGeometryUpdater;
  polylineVolumeGraphics: Cesium.PolylineVolumeGraphics;
  polylineVolumeOutlineGeometry: Cesium.PolylineVolumeOutlineGeometry;
  positionProperty: Cesium.PositionProperty;
  positionPropertyArray: Cesium.PositionPropertyArray;
  postProcessStage: Cesium.PostProcessStage;
  postProcessStageCollection: Cesium.PostProcessStageCollection;
  postProcessStageComposite: Cesium.PostProcessStageComposite;
  postProcessStageLibrary: Cesium.PostProcessStageLibrary;
  postProcessStageSampleMode: Cesium.PostProcessStageSampleMode;
  postProcessStageTextureCache: Cesium.PostProcessStageTextureCache;
  primitive: Cesium.Primitive;
  primitiveCollection: Cesium.PrimitiveCollection;
  primitivePipeline: Cesium.PrimitivePipeline;
  primitiveState: Cesium.PrimitiveState;
  primitiveType: Cesium.PrimitiveType;
  projectionPicker: Cesium.ProjectionPicker;
  projectionPickerViewModel: Cesium.ProjectionPickerViewModel;
  property: Cesium.Property;
  propertyArray: Cesium.PropertyArray;
  propertyBag: Cesium.PropertyBag;
  providerViewModel: Cesium.ProviderViewModel;
  proxy: Cesium.Proxy;
  quadraticRealPolynomial: Cesium.QuadraticRealPolynomial;
  quadtreeOccluders: Cesium.QuadtreeOccluders;
  quadtreePrimitive: Cesium.QuadtreePrimitive;
  quadtreeTile: Cesium.QuadtreeTile;
  quadtreeTileLoadState: Cesium.QuadtreeTileLoadState;
  quadtreeTileProvider: Cesium.QuadtreeTileProvider;
  quantizedMeshTerrainData: Cesium.QuantizedMeshTerrainData;
  quarticRealPolynomial: Cesium.QuarticRealPolynomial;
  quaternion: Cesium.Quaternion;
  quaternionSpline: Cesium.QuaternionSpline;
  queue: Cesium.Queue;
  ray: Cesium.Ray;
  rectangle: Cesium.Rectangle;
  rectangleCollisionChecker: Cesium.RectangleCollisionChecker;
  rectangleGeometry: Cesium.RectangleGeometry;
  rectangleGeometryLibrary: Cesium.RectangleGeometryLibrary;
  rectangleGeometryUpdater: Cesium.RectangleGeometryUpdater;
  rectangleGraphics: Cesium.RectangleGraphics;
  rectangleOutlineGeometry: Cesium.RectangleOutlineGeometry;
  referenceFrame: Cesium.ReferenceFrame;
  referenceProperty: Cesium.ReferenceProperty;
  renderState: Cesium.RenderState;
  renderbuffer: Cesium.Renderbuffer;
  renderbufferFormat: Cesium.RenderbufferFormat;
  request: Cesium.Request;
  requestErrorEvent: Cesium.RequestErrorEvent;
  requestScheduler: Cesium.RequestScheduler;
  requestState: Cesium.RequestState;
  requestType: Cesium.RequestType;
  resource: Cesium.Resource;
  rotation: Cesium.Rotation;
  runtimeError: Cesium.RuntimeError;
  sdfSettings: Cesium.SDFSettings;
  sampledPositionProperty: Cesium.SampledPositionProperty;
  sampledProperty: Cesium.SampledProperty;
  sampler: Cesium.Sampler;
  scaledPositionProperty: Cesium.ScaledPositionProperty;
  scene: Cesium.Scene;
  sceneFramebuffer: Cesium.SceneFramebuffer;
  sceneMode: Cesium.SceneMode;
  sceneModePicker: Cesium.SceneModePicker;
  sceneModePickerViewModel: Cesium.SceneModePickerViewModel;
  sceneTransforms: Cesium.SceneTransforms;
  sceneTransitioner: Cesium.SceneTransitioner;
  screenSpaceCameraController: Cesium.ScreenSpaceCameraController;
  screenSpaceEventHandler: Cesium.ScreenSpaceEventHandler;
  screenSpaceEventType: Cesium.ScreenSpaceEventType;
  selectionIndicator: Cesium.SelectionIndicator;
  selectionIndicatorViewModel: Cesium.SelectionIndicatorViewModel;
  shaderCache: Cesium.ShaderCache;
  shaderProgram: Cesium.ShaderProgram;
  shaderSource: Cesium.ShaderSource;
  shadowMap: Cesium.ShadowMap;
  shadowMapShader: Cesium.ShadowMapShader;
  shadowMode: Cesium.ShadowMode;
  shadowVolumeAppearance: Cesium.ShadowVolumeAppearance;
  showGeometryInstanceAttribute: Cesium.ShowGeometryInstanceAttribute;
  simon1994PlanetaryPositions: Cesium.Simon1994PlanetaryPositions;
  simplePolylineGeometry: Cesium.SimplePolylineGeometry;
  singleTileImageryProvider: Cesium.SingleTileImageryProvider;
  skyAtmosphere: Cesium.SkyAtmosphere;
  skyBox: Cesium.SkyBox;
  sphereEmitter: Cesium.SphereEmitter;
  sphereGeometry: Cesium.SphereGeometry;
  sphereOutlineGeometry: Cesium.SphereOutlineGeometry;
  spherical: Cesium.Spherical;
  spline: Cesium.Spline;
  staticGeometryColorBatch: Cesium.StaticGeometryColorBatch;
  staticGeometryPerMaterialBatch: Cesium.StaticGeometryPerMaterialBatch;
  staticGroundGeometryColorBatch: Cesium.StaticGroundGeometryColorBatch;
  staticGroundGeometryPerMaterialBatch: Cesium.StaticGroundGeometryPerMaterialBatch;
  staticGroundPolylinePerMaterialBatch: Cesium.StaticGroundPolylinePerMaterialBatch;
  staticOutlineGeometryBatch: Cesium.StaticOutlineGeometryBatch;
  stencilConstants: Cesium.StencilConstants;
  stencilFunction: Cesium.StencilFunction;
  stencilOperation: Cesium.StencilOperation;
  stripeMaterialProperty: Cesium.StripeMaterialProperty;
  stripeOrientation: Cesium.StripeOrientation;
  styleExpression: Cesium.StyleExpression;
  sun: Cesium.Sun;
  sunLight: Cesium.SunLight;
  sunPostProcess: Cesium.SunPostProcess;
  svgPathBindingHandler: Cesium.SvgPathBindingHandler;
  taskProcessor: Cesium.TaskProcessor;
  terrainData: Cesium.TerrainData;
  terrainEncoding: Cesium.TerrainEncoding;
  terrainFillMesh: Cesium.TerrainFillMesh;
  terrainMesh: Cesium.TerrainMesh;
  terrainOffsetProperty: Cesium.TerrainOffsetProperty;
  terrainProvider: Cesium.TerrainProvider;
  terrainQuantization: Cesium.TerrainQuantization;
  terrainState: Cesium.TerrainState;
  texture: Cesium.Texture;
  textureAtlas: Cesium.TextureAtlas;
  textureCache: Cesium.TextureCache;
  textureMagnificationFilter: Cesium.TextureMagnificationFilter;
  textureMinificationFilter: Cesium.TextureMinificationFilter;
  textureWrap: Cesium.TextureWrap;
  tileAvailability: Cesium.TileAvailability;
  tileBoundingRegion: Cesium.TileBoundingRegion;
  tileBoundingSphere: Cesium.TileBoundingSphere;
  tileBoundingVolume: Cesium.TileBoundingVolume;
  tileCoordinatesImageryProvider: Cesium.TileCoordinatesImageryProvider;
  tileDiscardPolicy: Cesium.TileDiscardPolicy;
  tileEdge: Cesium.TileEdge;
  tileImagery: Cesium.TileImagery;
  tileMapServiceImageryProvider: Cesium.TileMapServiceImageryProvider;
  tileOrientedBoundingBox: Cesium.TileOrientedBoundingBox;
  tileProviderError: Cesium.TileProviderError;
  tileReplacementQueue: Cesium.TileReplacementQueue;
  tileSelectionResult: Cesium.TileSelectionResult;
  tileState: Cesium.TileState;
  tileset3DTileContent: Cesium.Tileset3DTileContent;
  tilingScheme: Cesium.TilingScheme;
  timeConstants: Cesium.TimeConstants;
  timeDynamicImagery: Cesium.TimeDynamicImagery;
  timeDynamicPointCloud: Cesium.TimeDynamicPointCloud;
  timeInterval: Cesium.TimeInterval;
  timeIntervalCollection: Cesium.TimeIntervalCollection;
  timeIntervalCollectionPositionProperty: Cesium.TimeIntervalCollectionPositionProperty;
  timeIntervalCollectionProperty: Cesium.TimeIntervalCollectionProperty;
  timeStandard: Cesium.TimeStandard;
  timeline: Cesium.Timeline;
  timelineHighlightRange: Cesium.TimelineHighlightRange;
  timelineTrack: Cesium.TimelineTrack;
  tipsify: Cesium.Tipsify;
  toggleButtonViewModel: Cesium.ToggleButtonViewModel;
  tonemapper: Cesium.Tonemapper;
  transforms: Cesium.Transforms;
  translationRotationScale: Cesium.TranslationRotationScale;
  tridiagonalSystemSolver: Cesium.TridiagonalSystemSolver;
  trustedServers: Cesium.TrustedServers;
  tween: Cesium.Tween;
  tweenCollection: Cesium.TweenCollection;
  uniformState: Cesium.UniformState;
  uri: Cesium.Uri;
  urlTemplateImageryProvider: Cesium.UrlTemplateImageryProvider;
  version: Cesium.VERSION;
  vrButton: Cesium.VRButton;
  vrButtonViewModel: Cesium.VRButtonViewModel;
  vrTheWorldTerrainProvider: Cesium.VRTheWorldTerrainProvider;
  vector3DTileBatch: Cesium.Vector3DTileBatch;
  vector3DTileContent: Cesium.Vector3DTileContent;
  vector3DTileGeometry: Cesium.Vector3DTileGeometry;
  vector3DTilePoints: Cesium.Vector3DTilePoints;
  vector3DTilePolygons: Cesium.Vector3DTilePolygons;
  vector3DTilePolylines: Cesium.Vector3DTilePolylines;
  vector3DTilePrimitive: Cesium.Vector3DTilePrimitive;
  velocityOrientationProperty: Cesium.VelocityOrientationProperty;
  velocityVectorProperty: Cesium.VelocityVectorProperty;
  vertexArray: Cesium.VertexArray;
  vertexArrayFacade: Cesium.VertexArrayFacade;
  vertexFormat: Cesium.VertexFormat;
  verticalOrigin: Cesium.VerticalOrigin;
  videoSynchronizer: Cesium.VideoSynchronizer;
  view: Cesium.View;
  viewer: Cesium.Viewer;
  viewportQuad: Cesium.ViewportQuad;
  visibility: Cesium.Visibility;
  visualizer: Cesium.Visualizer;
  wallGeometry: Cesium.WallGeometry;
  wallGeometryLibrary: Cesium.WallGeometryLibrary;
  wallGeometryUpdater: Cesium.WallGeometryUpdater;
  wallGraphics: Cesium.WallGraphics;
  wallOutlineGeometry: Cesium.WallOutlineGeometry;
  webGlConstants: Cesium.WebGLConstants;
  webMapServiceImageryProvider: Cesium.WebMapServiceImageryProvider;
  webMapTileServiceImageryProvider: Cesium.WebMapTileServiceImageryProvider;
  webMercatorProjection: Cesium.WebMercatorProjection;
  webMercatorTilingScheme: Cesium.WebMercatorTilingScheme;
  weightSpline: Cesium.WeightSpline;
  windingOrder: Cesium.WindingOrder;
};

export type MappingTypeofExport = {
  animation: typeof Cesium["Animation"];
  animationViewModel: typeof Cesium["AnimationViewModel"];
  appearance: typeof Cesium["Appearance"];
  approximateTerrainHeights: typeof Cesium["ApproximateTerrainHeights"];
  arcGisTiledElevationTerrainProvider: typeof Cesium["ArcGISTiledElevationTerrainProvider"];
  arcGisMapServerImageryProvider: typeof Cesium["ArcGisMapServerImageryProvider"];
  arcType: typeof Cesium["ArcType"];
  associativeArray: typeof Cesium["AssociativeArray"];
  attributeCompression: typeof Cesium["AttributeCompression"];
  attributeType: typeof Cesium["AttributeType"];
  autoExposure: typeof Cesium["AutoExposure"];
  autolinker: typeof Cesium["Autolinker"];
  automaticUniforms: typeof Cesium["AutomaticUniforms"];
  axis: typeof Cesium["Axis"];
  axisAlignedBoundingBox: typeof Cesium["AxisAlignedBoundingBox"];
  baseLayerPicker: typeof Cesium["BaseLayerPicker"];
  baseLayerPickerViewModel: typeof Cesium["BaseLayerPickerViewModel"];
  batchTable: typeof Cesium["BatchTable"];
  batched3DModel3DTileContent: typeof Cesium["Batched3DModel3DTileContent"];
  billboard: typeof Cesium["Billboard"];
  billboardCollection: typeof Cesium["BillboardCollection"];
  billboardGraphics: typeof Cesium["BillboardGraphics"];
  billboardVisualizer: typeof Cesium["BillboardVisualizer"];
  bingMapsApi: typeof Cesium["BingMapsApi"];
  bingMapsGeocoderService: typeof Cesium["BingMapsGeocoderService"];
  bingMapsImageryProvider: typeof Cesium["BingMapsImageryProvider"];
  bingMapsStyle: typeof Cesium["BingMapsStyle"];
  blendEquation: typeof Cesium["BlendEquation"];
  blendFunction: typeof Cesium["BlendFunction"];
  blendOption: typeof Cesium["BlendOption"];
  blendingState: typeof Cesium["BlendingState"];
  boundingRectangle: typeof Cesium["BoundingRectangle"];
  boundingSphere: typeof Cesium["BoundingSphere"];
  boundingSphereState: typeof Cesium["BoundingSphereState"];
  boxEmitter: typeof Cesium["BoxEmitter"];
  boxGeometry: typeof Cesium["BoxGeometry"];
  boxGeometryUpdater: typeof Cesium["BoxGeometryUpdater"];
  boxGraphics: typeof Cesium["BoxGraphics"];
  boxOutlineGeometry: typeof Cesium["BoxOutlineGeometry"];
  brdfLutGenerator: typeof Cesium["BrdfLutGenerator"];
  buffer: typeof Cesium["Buffer"];
  bufferUsage: typeof Cesium["BufferUsage"];
  callbackProperty: typeof Cesium["CallbackProperty"];
  camera: typeof Cesium["Camera"];
  cameraEventAggregator: typeof Cesium["CameraEventAggregator"];
  cameraEventType: typeof Cesium["CameraEventType"];
  cameraFlightPath: typeof Cesium["CameraFlightPath"];
  cartesian2: typeof Cesium["Cartesian2"];
  cartesian3: typeof Cesium["Cartesian3"];
  cartesian4: typeof Cesium["Cartesian4"];
  cartographic: typeof Cesium["Cartographic"];
  cartographicGeocoderService: typeof Cesium["CartographicGeocoderService"];
  catmullRomSpline: typeof Cesium["CatmullRomSpline"];
  cesium3DTile: typeof Cesium["Cesium3DTile"];
  cesium3DTileBatchTable: typeof Cesium["Cesium3DTileBatchTable"];
  cesium3DTileColorBlendMode: typeof Cesium["Cesium3DTileColorBlendMode"];
  cesium3DTileContent: typeof Cesium["Cesium3DTileContent"];
  cesium3DTileContentFactory: typeof Cesium["Cesium3DTileContentFactory"];
  cesium3DTileContentState: typeof Cesium["Cesium3DTileContentState"];
  cesium3DTileFeature: typeof Cesium["Cesium3DTileFeature"];
  cesium3DTileFeatureTable: typeof Cesium["Cesium3DTileFeatureTable"];
  cesium3DTileOptimizationHint: typeof Cesium["Cesium3DTileOptimizationHint"];
  cesium3DTileOptimizations: typeof Cesium["Cesium3DTileOptimizations"];
  cesium3DTilePass: typeof Cesium["Cesium3DTilePass"];
  cesium3DTilePassState: typeof Cesium["Cesium3DTilePassState"];
  cesium3DTilePointFeature: typeof Cesium["Cesium3DTilePointFeature"];
  cesium3DTileRefine: typeof Cesium["Cesium3DTileRefine"];
  cesium3DTileStyle: typeof Cesium["Cesium3DTileStyle"];
  cesium3DTileStyleEngine: typeof Cesium["Cesium3DTileStyleEngine"];
  cesium3DTilesInspector: typeof Cesium["Cesium3DTilesInspector"];
  cesium3DTilesInspectorViewModel: typeof Cesium["Cesium3DTilesInspectorViewModel"];
  cesium3DTileset: typeof Cesium["Cesium3DTileset"];
  cesium3DTilesetCache: typeof Cesium["Cesium3DTilesetCache"];
  cesium3DTilesetGraphics: typeof Cesium["Cesium3DTilesetGraphics"];
  cesium3DTilesetHeatmap: typeof Cesium["Cesium3DTilesetHeatmap"];
  cesium3DTilesetMostDetailedTraversal: typeof Cesium["Cesium3DTilesetMostDetailedTraversal"];
  cesium3DTilesetStatistics: typeof Cesium["Cesium3DTilesetStatistics"];
  cesium3DTilesetTraversal: typeof Cesium["Cesium3DTilesetTraversal"];
  cesium3DTilesetVisualizer: typeof Cesium["Cesium3DTilesetVisualizer"];
  cesiumInspector: typeof Cesium["CesiumInspector"];
  cesiumInspectorViewModel: typeof Cesium["CesiumInspectorViewModel"];
  cesiumTerrainProvider: typeof Cesium["CesiumTerrainProvider"];
  cesiumWidget: typeof Cesium["CesiumWidget"];
  check: typeof Cesium["Check"];
  checkerboardMaterialProperty: typeof Cesium["CheckerboardMaterialProperty"];
  circleEmitter: typeof Cesium["CircleEmitter"];
  circleGeometry: typeof Cesium["CircleGeometry"];
  circleOutlineGeometry: typeof Cesium["CircleOutlineGeometry"];
  classificationModel: typeof Cesium["ClassificationModel"];
  classificationPrimitive: typeof Cesium["ClassificationPrimitive"];
  classificationType: typeof Cesium["ClassificationType"];
  clearCommand: typeof Cesium["ClearCommand"];
  clippingPlane: typeof Cesium["ClippingPlane"];
  clippingPlaneCollection: typeof Cesium["ClippingPlaneCollection"];
  clock: typeof Cesium["Clock"];
  clockRange: typeof Cesium["ClockRange"];
  clockStep: typeof Cesium["ClockStep"];
  clockViewModel: typeof Cesium["ClockViewModel"];
  color: typeof Cesium["Color"];
  colorBlendMode: typeof Cesium["ColorBlendMode"];
  colorGeometryInstanceAttribute: typeof Cesium["ColorGeometryInstanceAttribute"];
  colorMaterialProperty: typeof Cesium["ColorMaterialProperty"];
  command: typeof Cesium["Command"];
  componentDatatype: typeof Cesium["ComponentDatatype"];
  composite3DTileContent: typeof Cesium["Composite3DTileContent"];
  compositeEntityCollection: typeof Cesium["CompositeEntityCollection"];
  compositeMaterialProperty: typeof Cesium["CompositeMaterialProperty"];
  compositePositionProperty: typeof Cesium["CompositePositionProperty"];
  compositeProperty: typeof Cesium["CompositeProperty"];
  compressedTextureBuffer: typeof Cesium["CompressedTextureBuffer"];
  computeCommand: typeof Cesium["ComputeCommand"];
  computeEngine: typeof Cesium["ComputeEngine"];
  conditionsExpression: typeof Cesium["ConditionsExpression"];
  coneEmitter: typeof Cesium["ConeEmitter"];
  constantPositionProperty: typeof Cesium["ConstantPositionProperty"];
  constantProperty: typeof Cesium["ConstantProperty"];
  context: typeof Cesium["Context"];
  contextLimits: typeof Cesium["ContextLimits"];
  coplanarPolygonGeometry: typeof Cesium["CoplanarPolygonGeometry"];
  coplanarPolygonGeometryLibrary: typeof Cesium["CoplanarPolygonGeometryLibrary"];
  coplanarPolygonOutlineGeometry: typeof Cesium["CoplanarPolygonOutlineGeometry"];
  cornerType: typeof Cesium["CornerType"];
  corridorGeometry: typeof Cesium["CorridorGeometry"];
  corridorGeometryLibrary: typeof Cesium["CorridorGeometryLibrary"];
  corridorGeometryUpdater: typeof Cesium["CorridorGeometryUpdater"];
  corridorGraphics: typeof Cesium["CorridorGraphics"];
  corridorOutlineGeometry: typeof Cesium["CorridorOutlineGeometry"];
  credit: typeof Cesium["Credit"];
  creditDisplay: typeof Cesium["CreditDisplay"];
  cubeMap: typeof Cesium["CubeMap"];
  cubeMapFace: typeof Cesium["CubeMapFace"];
  cubicRealPolynomial: typeof Cesium["CubicRealPolynomial"];
  cullFace: typeof Cesium["CullFace"];
  cullingVolume: typeof Cesium["CullingVolume"];
  customDataSource: typeof Cesium["CustomDataSource"];
  cylinderGeometry: typeof Cesium["CylinderGeometry"];
  cylinderGeometryLibrary: typeof Cesium["CylinderGeometryLibrary"];
  cylinderGeometryUpdater: typeof Cesium["CylinderGeometryUpdater"];
  cylinderGraphics: typeof Cesium["CylinderGraphics"];
  cylinderOutlineGeometry: typeof Cesium["CylinderOutlineGeometry"];
  czmlDataSource: typeof Cesium["CzmlDataSource"];
  dataSource: typeof Cesium["DataSource"];
  dataSourceClock: typeof Cesium["DataSourceClock"];
  dataSourceCollection: typeof Cesium["DataSourceCollection"];
  dataSourceDisplay: typeof Cesium["DataSourceDisplay"];
  debugAppearance: typeof Cesium["DebugAppearance"];
  debugCameraPrimitive: typeof Cesium["DebugCameraPrimitive"];
  debugModelMatrixPrimitive: typeof Cesium["DebugModelMatrixPrimitive"];
  defaultProxy: typeof Cesium["DefaultProxy"];
  depthFunction: typeof Cesium["DepthFunction"];
  depthPlane: typeof Cesium["DepthPlane"];
  derivedCommand: typeof Cesium["DerivedCommand"];
  developerError: typeof Cesium["DeveloperError"];
  deviceOrientationCameraController: typeof Cesium["DeviceOrientationCameraController"];
  directionalLight: typeof Cesium["DirectionalLight"];
  discardEmptyTileImagePolicy: typeof Cesium["DiscardEmptyTileImagePolicy"];
  discardMissingTileImagePolicy: typeof Cesium["DiscardMissingTileImagePolicy"];
  distanceDisplayCondition: typeof Cesium["DistanceDisplayCondition"];
  distanceDisplayConditionGeometryInstanceAttribute: typeof Cesium["DistanceDisplayConditionGeometryInstanceAttribute"];
  doublyLinkedList: typeof Cesium["DoublyLinkedList"];
  dracoLoader: typeof Cesium["DracoLoader"];
  drawCommand: typeof Cesium["DrawCommand"];
  dynamicGeometryBatch: typeof Cesium["DynamicGeometryBatch"];
  dynamicGeometryUpdater: typeof Cesium["DynamicGeometryUpdater"];
  earthOrientationParameters: typeof Cesium["EarthOrientationParameters"];
  earthOrientationParametersSample: typeof Cesium["EarthOrientationParametersSample"];
  easingFunction: typeof Cesium["EasingFunction"];
  ellipseGeometry: typeof Cesium["EllipseGeometry"];
  ellipseGeometryLibrary: typeof Cesium["EllipseGeometryLibrary"];
  ellipseGeometryUpdater: typeof Cesium["EllipseGeometryUpdater"];
  ellipseGraphics: typeof Cesium["EllipseGraphics"];
  ellipseOutlineGeometry: typeof Cesium["EllipseOutlineGeometry"];
  ellipsoid: typeof Cesium["Ellipsoid"];
  ellipsoidGeodesic: typeof Cesium["EllipsoidGeodesic"];
  ellipsoidGeometry: typeof Cesium["EllipsoidGeometry"];
  ellipsoidGeometryUpdater: typeof Cesium["EllipsoidGeometryUpdater"];
  ellipsoidGraphics: typeof Cesium["EllipsoidGraphics"];
  ellipsoidOutlineGeometry: typeof Cesium["EllipsoidOutlineGeometry"];
  ellipsoidPrimitive: typeof Cesium["EllipsoidPrimitive"];
  ellipsoidRhumbLine: typeof Cesium["EllipsoidRhumbLine"];
  ellipsoidSurfaceAppearance: typeof Cesium["EllipsoidSurfaceAppearance"];
  ellipsoidTangentPlane: typeof Cesium["EllipsoidTangentPlane"];
  ellipsoidTerrainProvider: typeof Cesium["EllipsoidTerrainProvider"];
  ellipsoidalOccluder: typeof Cesium["EllipsoidalOccluder"];
  empty3DTileContent: typeof Cesium["Empty3DTileContent"];
  encodedCartesian3: typeof Cesium["EncodedCartesian3"];
  entity: typeof Cesium["Entity"];
  entityCluster: typeof Cesium["EntityCluster"];
  entityCollection: typeof Cesium["EntityCollection"];
  entityView: typeof Cesium["EntityView"];
  event: typeof Cesium["Event"];
  eventHelper: typeof Cesium["EventHelper"];
  expression: typeof Cesium["Expression"];
  expressionNodeType: typeof Cesium["ExpressionNodeType"];
  extrapolationType: typeof Cesium["ExtrapolationType"];
  fxaa311: typeof Cesium["FXAA3_11"];
  featureDetection: typeof Cesium["FeatureDetection"];
  fog: typeof Cesium["Fog"];
  forEach: typeof Cesium["ForEach"];
  frameRateMonitor: typeof Cesium["FrameRateMonitor"];
  frameState: typeof Cesium["FrameState"];
  framebuffer: typeof Cesium["Framebuffer"];
  frustumCommands: typeof Cesium["FrustumCommands"];
  frustumGeometry: typeof Cesium["FrustumGeometry"];
  frustumOutlineGeometry: typeof Cesium["FrustumOutlineGeometry"];
  fullscreen: typeof Cesium["Fullscreen"];
  fullscreenButton: typeof Cesium["FullscreenButton"];
  fullscreenButtonViewModel: typeof Cesium["FullscreenButtonViewModel"];
  geoJsonDataSource: typeof Cesium["GeoJsonDataSource"];
  geocodeType: typeof Cesium["GeocodeType"];
  geocoder: typeof Cesium["Geocoder"];
  geocoderService: typeof Cesium["GeocoderService"];
  geocoderViewModel: typeof Cesium["GeocoderViewModel"];
  geographicProjection: typeof Cesium["GeographicProjection"];
  geographicTilingScheme: typeof Cesium["GeographicTilingScheme"];
  geometry: typeof Cesium["Geometry"];
  geometry3DTileContent: typeof Cesium["Geometry3DTileContent"];
  geometryAttribute: typeof Cesium["GeometryAttribute"];
  geometryAttributes: typeof Cesium["GeometryAttributes"];
  geometryInstance: typeof Cesium["GeometryInstance"];
  geometryInstanceAttribute: typeof Cesium["GeometryInstanceAttribute"];
  geometryOffsetAttribute: typeof Cesium["GeometryOffsetAttribute"];
  geometryPipeline: typeof Cesium["GeometryPipeline"];
  geometryType: typeof Cesium["GeometryType"];
  geometryUpdater: typeof Cesium["GeometryUpdater"];
  geometryVisualizer: typeof Cesium["GeometryVisualizer"];
  getFeatureInfoFormat: typeof Cesium["GetFeatureInfoFormat"];
  globe: typeof Cesium["Globe"];
  globeDepth: typeof Cesium["GlobeDepth"];
  globeSurfaceShaderSet: typeof Cesium["GlobeSurfaceShaderSet"];
  globeSurfaceTile: typeof Cesium["GlobeSurfaceTile"];
  globeSurfaceTileProvider: typeof Cesium["GlobeSurfaceTileProvider"];
  globeTranslucency: typeof Cesium["GlobeTranslucency"];
  globeTranslucencyFramebuffer: typeof Cesium["GlobeTranslucencyFramebuffer"];
  globeTranslucencyState: typeof Cesium["GlobeTranslucencyState"];
  googleEarthEnterpriseImageryProvider: typeof Cesium["GoogleEarthEnterpriseImageryProvider"];
  googleEarthEnterpriseMapsProvider: typeof Cesium["GoogleEarthEnterpriseMapsProvider"];
  googleEarthEnterpriseMetadata: typeof Cesium["GoogleEarthEnterpriseMetadata"];
  googleEarthEnterpriseTerrainData: typeof Cesium["GoogleEarthEnterpriseTerrainData"];
  googleEarthEnterpriseTerrainProvider: typeof Cesium["GoogleEarthEnterpriseTerrainProvider"];
  googleEarthEnterpriseTileInformation: typeof Cesium["GoogleEarthEnterpriseTileInformation"];
  gregorianDate: typeof Cesium["GregorianDate"];
  gridImageryProvider: typeof Cesium["GridImageryProvider"];
  gridMaterialProperty: typeof Cesium["GridMaterialProperty"];
  groundGeometryUpdater: typeof Cesium["GroundGeometryUpdater"];
  groundPolylineGeometry: typeof Cesium["GroundPolylineGeometry"];
  groundPolylinePrimitive: typeof Cesium["GroundPolylinePrimitive"];
  groundPrimitive: typeof Cesium["GroundPrimitive"];
  headingPitchRange: typeof Cesium["HeadingPitchRange"];
  headingPitchRoll: typeof Cesium["HeadingPitchRoll"];
  heap: typeof Cesium["Heap"];
  heightReference: typeof Cesium["HeightReference"];
  heightmapEncoding: typeof Cesium["HeightmapEncoding"];
  heightmapTerrainData: typeof Cesium["HeightmapTerrainData"];
  heightmapTessellator: typeof Cesium["HeightmapTessellator"];
  hermitePolynomialApproximation: typeof Cesium["HermitePolynomialApproximation"];
  hermiteSpline: typeof Cesium["HermiteSpline"];
  homeButton: typeof Cesium["HomeButton"];
  homeButtonViewModel: typeof Cesium["HomeButtonViewModel"];
  horizontalOrigin: typeof Cesium["HorizontalOrigin"];
  iau2000Orientation: typeof Cesium["Iau2000Orientation"];
  iau2006XysData: typeof Cesium["Iau2006XysData"];
  iau2006XysSample: typeof Cesium["Iau2006XysSample"];
  iauOrientationAxes: typeof Cesium["IauOrientationAxes"];
  iauOrientationParameters: typeof Cesium["IauOrientationParameters"];
  imageMaterialProperty: typeof Cesium["ImageMaterialProperty"];
  imagery: typeof Cesium["Imagery"];
  imageryLayer: typeof Cesium["ImageryLayer"];
  imageryLayerCollection: typeof Cesium["ImageryLayerCollection"];
  imageryLayerFeatureInfo: typeof Cesium["ImageryLayerFeatureInfo"];
  imageryProvider: typeof Cesium["ImageryProvider"];
  imagerySplitDirection: typeof Cesium["ImagerySplitDirection"];
  imageryState: typeof Cesium["ImageryState"];
  indexDatatype: typeof Cesium["IndexDatatype"];
  infoBox: typeof Cesium["InfoBox"];
  infoBoxViewModel: typeof Cesium["InfoBoxViewModel"];
  inspectorShared: typeof Cesium["InspectorShared"];
  instanced3DModel3DTileContent: typeof Cesium["Instanced3DModel3DTileContent"];
  interpolationAlgorithm: typeof Cesium["InterpolationAlgorithm"];
  intersect: typeof Cesium["Intersect"];
  intersectionTests: typeof Cesium["IntersectionTests"];
  intersections2D: typeof Cesium["Intersections2D"];
  interval: typeof Cesium["Interval"];
  invertClassification: typeof Cesium["InvertClassification"];
  ion: typeof Cesium["Ion"];
  ionGeocoderService: typeof Cesium["IonGeocoderService"];
  ionImageryProvider: typeof Cesium["IonImageryProvider"];
  ionResource: typeof Cesium["IonResource"];
  ionWorldImageryStyle: typeof Cesium["IonWorldImageryStyle"];
  iso8601: typeof Cesium["Iso8601"];
  jobScheduler: typeof Cesium["JobScheduler"];
  jobType: typeof Cesium["JobType"];
  julianDate: typeof Cesium["JulianDate"];
  keyboardEventModifier: typeof Cesium["KeyboardEventModifier"];
  kmlCamera: typeof Cesium["KmlCamera"];
  kmlDataSource: typeof Cesium["KmlDataSource"];
  kmlLookAt: typeof Cesium["KmlLookAt"];
  kmlTour: typeof Cesium["KmlTour"];
  kmlTourFlyTo: typeof Cesium["KmlTourFlyTo"];
  kmlTourWait: typeof Cesium["KmlTourWait"];
  label: typeof Cesium["Label"];
  labelCollection: typeof Cesium["LabelCollection"];
  labelGraphics: typeof Cesium["LabelGraphics"];
  labelStyle: typeof Cesium["LabelStyle"];
  labelVisualizer: typeof Cesium["LabelVisualizer"];
  lagrangePolynomialApproximation: typeof Cesium["LagrangePolynomialApproximation"];
  leapSecond: typeof Cesium["LeapSecond"];
  lercDecode: typeof Cesium["LercDecode"];
  light: typeof Cesium["Light"];
  linearApproximation: typeof Cesium["LinearApproximation"];
  linearSpline: typeof Cesium["LinearSpline"];
  managedArray: typeof Cesium["ManagedArray"];
  mapMode2D: typeof Cesium["MapMode2D"];
  mapProjection: typeof Cesium["MapProjection"];
  mapboxApi: typeof Cesium["MapboxApi"];
  mapboxImageryProvider: typeof Cesium["MapboxImageryProvider"];
  mapboxStyleImageryProvider: typeof Cesium["MapboxStyleImageryProvider"];
  material: typeof Cesium["Material"];
  materialAppearance: typeof Cesium["MaterialAppearance"];
  materialProperty: typeof Cesium["MaterialProperty"];
  math: typeof Cesium["Math"];
  matrix2: typeof Cesium["Matrix2"];
  matrix3: typeof Cesium["Matrix3"];
  matrix4: typeof Cesium["Matrix4"];
  mipmapHint: typeof Cesium["MipmapHint"];
  model: typeof Cesium["Model"];
  modelAnimation: typeof Cesium["ModelAnimation"];
  modelAnimationCache: typeof Cesium["ModelAnimationCache"];
  modelAnimationCollection: typeof Cesium["ModelAnimationCollection"];
  modelAnimationLoop: typeof Cesium["ModelAnimationLoop"];
  modelAnimationState: typeof Cesium["ModelAnimationState"];
  modelGraphics: typeof Cesium["ModelGraphics"];
  modelInstance: typeof Cesium["ModelInstance"];
  modelInstanceCollection: typeof Cesium["ModelInstanceCollection"];
  modelLoadResources: typeof Cesium["ModelLoadResources"];
  modelMaterial: typeof Cesium["ModelMaterial"];
  modelMesh: typeof Cesium["ModelMesh"];
  modelNode: typeof Cesium["ModelNode"];
  modelOutlineLoader: typeof Cesium["ModelOutlineLoader"];
  modelUtility: typeof Cesium["ModelUtility"];
  modelVisualizer: typeof Cesium["ModelVisualizer"];
  moon: typeof Cesium["Moon"];
  navigationHelpButton: typeof Cesium["NavigationHelpButton"];
  navigationHelpButtonViewModel: typeof Cesium["NavigationHelpButtonViewModel"];
  nearFarScalar: typeof Cesium["NearFarScalar"];
  neverTileDiscardPolicy: typeof Cesium["NeverTileDiscardPolicy"];
  noSleep: typeof Cesium["NoSleep"];
  nodeTransformationProperty: typeof Cesium["NodeTransformationProperty"];
  oit: typeof Cesium["OIT"];
  occluder: typeof Cesium["Occluder"];
  octahedralProjectedCubeMap: typeof Cesium["OctahedralProjectedCubeMap"];
  offsetGeometryInstanceAttribute: typeof Cesium["OffsetGeometryInstanceAttribute"];
  openCageGeocoderService: typeof Cesium["OpenCageGeocoderService"];
  openStreetMapImageryProvider: typeof Cesium["OpenStreetMapImageryProvider"];
  orderedGroundPrimitiveCollection: typeof Cesium["OrderedGroundPrimitiveCollection"];
  orientedBoundingBox: typeof Cesium["OrientedBoundingBox"];
  orthographicFrustum: typeof Cesium["OrthographicFrustum"];
  orthographicOffCenterFrustum: typeof Cesium["OrthographicOffCenterFrustum"];
  packable: typeof Cesium["Packable"];
  packableForInterpolation: typeof Cesium["PackableForInterpolation"];
  particle: typeof Cesium["Particle"];
  particleBurst: typeof Cesium["ParticleBurst"];
  particleEmitter: typeof Cesium["ParticleEmitter"];
  particleSystem: typeof Cesium["ParticleSystem"];
  pass: typeof Cesium["Pass"];
  passState: typeof Cesium["PassState"];
  pathGraphics: typeof Cesium["PathGraphics"];
  pathVisualizer: typeof Cesium["PathVisualizer"];
  peliasGeocoderService: typeof Cesium["PeliasGeocoderService"];
  perInstanceColorAppearance: typeof Cesium["PerInstanceColorAppearance"];
  performanceDisplay: typeof Cesium["PerformanceDisplay"];
  performanceWatchdog: typeof Cesium["PerformanceWatchdog"];
  performanceWatchdogViewModel: typeof Cesium["PerformanceWatchdogViewModel"];
  perspectiveFrustum: typeof Cesium["PerspectiveFrustum"];
  perspectiveOffCenterFrustum: typeof Cesium["PerspectiveOffCenterFrustum"];
  pickDepth: typeof Cesium["PickDepth"];
  pickDepthFramebuffer: typeof Cesium["PickDepthFramebuffer"];
  pickFramebuffer: typeof Cesium["PickFramebuffer"];
  picking: typeof Cesium["Picking"];
  pinBuilder: typeof Cesium["PinBuilder"];
  pixelDatatype: typeof Cesium["PixelDatatype"];
  pixelFormat: typeof Cesium["PixelFormat"];
  plane: typeof Cesium["Plane"];
  planeGeometry: typeof Cesium["PlaneGeometry"];
  planeGeometryUpdater: typeof Cesium["PlaneGeometryUpdater"];
  planeGraphics: typeof Cesium["PlaneGraphics"];
  planeOutlineGeometry: typeof Cesium["PlaneOutlineGeometry"];
  pointCloud: typeof Cesium["PointCloud"];
  pointCloud3DTileContent: typeof Cesium["PointCloud3DTileContent"];
  pointCloudEyeDomeLighting: typeof Cesium["PointCloudEyeDomeLighting"];
  pointCloudShading: typeof Cesium["PointCloudShading"];
  pointGraphics: typeof Cesium["PointGraphics"];
  pointPrimitive: typeof Cesium["PointPrimitive"];
  pointPrimitiveCollection: typeof Cesium["PointPrimitiveCollection"];
  pointVisualizer: typeof Cesium["PointVisualizer"];
  polygonGeometry: typeof Cesium["PolygonGeometry"];
  polygonGeometryLibrary: typeof Cesium["PolygonGeometryLibrary"];
  polygonGeometryUpdater: typeof Cesium["PolygonGeometryUpdater"];
  polygonGraphics: typeof Cesium["PolygonGraphics"];
  polygonHierarchy: typeof Cesium["PolygonHierarchy"];
  polygonOutlineGeometry: typeof Cesium["PolygonOutlineGeometry"];
  polygonPipeline: typeof Cesium["PolygonPipeline"];
  polyline: typeof Cesium["Polyline"];
  polylineArrowMaterialProperty: typeof Cesium["PolylineArrowMaterialProperty"];
  polylineCollection: typeof Cesium["PolylineCollection"];
  polylineColorAppearance: typeof Cesium["PolylineColorAppearance"];
  polylineDashMaterialProperty: typeof Cesium["PolylineDashMaterialProperty"];
  polylineGeometry: typeof Cesium["PolylineGeometry"];
  polylineGeometryUpdater: typeof Cesium["PolylineGeometryUpdater"];
  polylineGlowMaterialProperty: typeof Cesium["PolylineGlowMaterialProperty"];
  polylineGraphics: typeof Cesium["PolylineGraphics"];
  polylineMaterialAppearance: typeof Cesium["PolylineMaterialAppearance"];
  polylineOutlineMaterialProperty: typeof Cesium["PolylineOutlineMaterialProperty"];
  polylinePipeline: typeof Cesium["PolylinePipeline"];
  polylineVisualizer: typeof Cesium["PolylineVisualizer"];
  polylineVolumeGeometry: typeof Cesium["PolylineVolumeGeometry"];
  polylineVolumeGeometryLibrary: typeof Cesium["PolylineVolumeGeometryLibrary"];
  polylineVolumeGeometryUpdater: typeof Cesium["PolylineVolumeGeometryUpdater"];
  polylineVolumeGraphics: typeof Cesium["PolylineVolumeGraphics"];
  polylineVolumeOutlineGeometry: typeof Cesium["PolylineVolumeOutlineGeometry"];
  positionProperty: typeof Cesium["PositionProperty"];
  positionPropertyArray: typeof Cesium["PositionPropertyArray"];
  postProcessStage: typeof Cesium["PostProcessStage"];
  postProcessStageCollection: typeof Cesium["PostProcessStageCollection"];
  postProcessStageComposite: typeof Cesium["PostProcessStageComposite"];
  postProcessStageLibrary: typeof Cesium["PostProcessStageLibrary"];
  postProcessStageSampleMode: typeof Cesium["PostProcessStageSampleMode"];
  postProcessStageTextureCache: typeof Cesium["PostProcessStageTextureCache"];
  primitive: typeof Cesium["Primitive"];
  primitiveCollection: typeof Cesium["PrimitiveCollection"];
  primitivePipeline: typeof Cesium["PrimitivePipeline"];
  primitiveState: typeof Cesium["PrimitiveState"];
  primitiveType: typeof Cesium["PrimitiveType"];
  projectionPicker: typeof Cesium["ProjectionPicker"];
  projectionPickerViewModel: typeof Cesium["ProjectionPickerViewModel"];
  property: typeof Cesium["Property"];
  propertyArray: typeof Cesium["PropertyArray"];
  propertyBag: typeof Cesium["PropertyBag"];
  providerViewModel: typeof Cesium["ProviderViewModel"];
  proxy: typeof Cesium["Proxy"];
  quadraticRealPolynomial: typeof Cesium["QuadraticRealPolynomial"];
  quadtreeOccluders: typeof Cesium["QuadtreeOccluders"];
  quadtreePrimitive: typeof Cesium["QuadtreePrimitive"];
  quadtreeTile: typeof Cesium["QuadtreeTile"];
  quadtreeTileLoadState: typeof Cesium["QuadtreeTileLoadState"];
  quadtreeTileProvider: typeof Cesium["QuadtreeTileProvider"];
  quantizedMeshTerrainData: typeof Cesium["QuantizedMeshTerrainData"];
  quarticRealPolynomial: typeof Cesium["QuarticRealPolynomial"];
  quaternion: typeof Cesium["Quaternion"];
  quaternionSpline: typeof Cesium["QuaternionSpline"];
  queue: typeof Cesium["Queue"];
  ray: typeof Cesium["Ray"];
  rectangle: typeof Cesium["Rectangle"];
  rectangleCollisionChecker: typeof Cesium["RectangleCollisionChecker"];
  rectangleGeometry: typeof Cesium["RectangleGeometry"];
  rectangleGeometryLibrary: typeof Cesium["RectangleGeometryLibrary"];
  rectangleGeometryUpdater: typeof Cesium["RectangleGeometryUpdater"];
  rectangleGraphics: typeof Cesium["RectangleGraphics"];
  rectangleOutlineGeometry: typeof Cesium["RectangleOutlineGeometry"];
  referenceFrame: typeof Cesium["ReferenceFrame"];
  referenceProperty: typeof Cesium["ReferenceProperty"];
  renderState: typeof Cesium["RenderState"];
  renderbuffer: typeof Cesium["Renderbuffer"];
  renderbufferFormat: typeof Cesium["RenderbufferFormat"];
  request: typeof Cesium["Request"];
  requestErrorEvent: typeof Cesium["RequestErrorEvent"];
  requestScheduler: typeof Cesium["RequestScheduler"];
  requestState: typeof Cesium["RequestState"];
  requestType: typeof Cesium["RequestType"];
  resource: typeof Cesium["Resource"];
  rotation: typeof Cesium["Rotation"];
  runtimeError: typeof Cesium["RuntimeError"];
  sdfSettings: typeof Cesium["SDFSettings"];
  sampledPositionProperty: typeof Cesium["SampledPositionProperty"];
  sampledProperty: typeof Cesium["SampledProperty"];
  sampler: typeof Cesium["Sampler"];
  scaledPositionProperty: typeof Cesium["ScaledPositionProperty"];
  scene: typeof Cesium["Scene"];
  sceneFramebuffer: typeof Cesium["SceneFramebuffer"];
  sceneMode: typeof Cesium["SceneMode"];
  sceneModePicker: typeof Cesium["SceneModePicker"];
  sceneModePickerViewModel: typeof Cesium["SceneModePickerViewModel"];
  sceneTransforms: typeof Cesium["SceneTransforms"];
  sceneTransitioner: typeof Cesium["SceneTransitioner"];
  screenSpaceCameraController: typeof Cesium["ScreenSpaceCameraController"];
  screenSpaceEventHandler: typeof Cesium["ScreenSpaceEventHandler"];
  screenSpaceEventType: typeof Cesium["ScreenSpaceEventType"];
  selectionIndicator: typeof Cesium["SelectionIndicator"];
  selectionIndicatorViewModel: typeof Cesium["SelectionIndicatorViewModel"];
  shaderCache: typeof Cesium["ShaderCache"];
  shaderProgram: typeof Cesium["ShaderProgram"];
  shaderSource: typeof Cesium["ShaderSource"];
  shadowMap: typeof Cesium["ShadowMap"];
  shadowMapShader: typeof Cesium["ShadowMapShader"];
  shadowMode: typeof Cesium["ShadowMode"];
  shadowVolumeAppearance: typeof Cesium["ShadowVolumeAppearance"];
  showGeometryInstanceAttribute: typeof Cesium["ShowGeometryInstanceAttribute"];
  simon1994PlanetaryPositions: typeof Cesium["Simon1994PlanetaryPositions"];
  simplePolylineGeometry: typeof Cesium["SimplePolylineGeometry"];
  singleTileImageryProvider: typeof Cesium["SingleTileImageryProvider"];
  skyAtmosphere: typeof Cesium["SkyAtmosphere"];
  skyBox: typeof Cesium["SkyBox"];
  sphereEmitter: typeof Cesium["SphereEmitter"];
  sphereGeometry: typeof Cesium["SphereGeometry"];
  sphereOutlineGeometry: typeof Cesium["SphereOutlineGeometry"];
  spherical: typeof Cesium["Spherical"];
  spline: typeof Cesium["Spline"];
  staticGeometryColorBatch: typeof Cesium["StaticGeometryColorBatch"];
  staticGeometryPerMaterialBatch: typeof Cesium["StaticGeometryPerMaterialBatch"];
  staticGroundGeometryColorBatch: typeof Cesium["StaticGroundGeometryColorBatch"];
  staticGroundGeometryPerMaterialBatch: typeof Cesium["StaticGroundGeometryPerMaterialBatch"];
  staticGroundPolylinePerMaterialBatch: typeof Cesium["StaticGroundPolylinePerMaterialBatch"];
  staticOutlineGeometryBatch: typeof Cesium["StaticOutlineGeometryBatch"];
  stencilConstants: typeof Cesium["StencilConstants"];
  stencilFunction: typeof Cesium["StencilFunction"];
  stencilOperation: typeof Cesium["StencilOperation"];
  stripeMaterialProperty: typeof Cesium["StripeMaterialProperty"];
  stripeOrientation: typeof Cesium["StripeOrientation"];
  styleExpression: typeof Cesium["StyleExpression"];
  sun: typeof Cesium["Sun"];
  sunLight: typeof Cesium["SunLight"];
  sunPostProcess: typeof Cesium["SunPostProcess"];
  svgPathBindingHandler: typeof Cesium["SvgPathBindingHandler"];
  taskProcessor: typeof Cesium["TaskProcessor"];
  terrainData: typeof Cesium["TerrainData"];
  terrainEncoding: typeof Cesium["TerrainEncoding"];
  terrainFillMesh: typeof Cesium["TerrainFillMesh"];
  terrainMesh: typeof Cesium["TerrainMesh"];
  terrainOffsetProperty: typeof Cesium["TerrainOffsetProperty"];
  terrainProvider: typeof Cesium["TerrainProvider"];
  terrainQuantization: typeof Cesium["TerrainQuantization"];
  terrainState: typeof Cesium["TerrainState"];
  texture: typeof Cesium["Texture"];
  textureAtlas: typeof Cesium["TextureAtlas"];
  textureCache: typeof Cesium["TextureCache"];
  textureMagnificationFilter: typeof Cesium["TextureMagnificationFilter"];
  textureMinificationFilter: typeof Cesium["TextureMinificationFilter"];
  textureWrap: typeof Cesium["TextureWrap"];
  tileAvailability: typeof Cesium["TileAvailability"];
  tileBoundingRegion: typeof Cesium["TileBoundingRegion"];
  tileBoundingSphere: typeof Cesium["TileBoundingSphere"];
  tileBoundingVolume: typeof Cesium["TileBoundingVolume"];
  tileCoordinatesImageryProvider: typeof Cesium["TileCoordinatesImageryProvider"];
  tileDiscardPolicy: typeof Cesium["TileDiscardPolicy"];
  tileEdge: typeof Cesium["TileEdge"];
  tileImagery: typeof Cesium["TileImagery"];
  tileMapServiceImageryProvider: typeof Cesium["TileMapServiceImageryProvider"];
  tileOrientedBoundingBox: typeof Cesium["TileOrientedBoundingBox"];
  tileProviderError: typeof Cesium["TileProviderError"];
  tileReplacementQueue: typeof Cesium["TileReplacementQueue"];
  tileSelectionResult: typeof Cesium["TileSelectionResult"];
  tileState: typeof Cesium["TileState"];
  tileset3DTileContent: typeof Cesium["Tileset3DTileContent"];
  tilingScheme: typeof Cesium["TilingScheme"];
  timeConstants: typeof Cesium["TimeConstants"];
  timeDynamicImagery: typeof Cesium["TimeDynamicImagery"];
  timeDynamicPointCloud: typeof Cesium["TimeDynamicPointCloud"];
  timeInterval: typeof Cesium["TimeInterval"];
  timeIntervalCollection: typeof Cesium["TimeIntervalCollection"];
  timeIntervalCollectionPositionProperty: typeof Cesium["TimeIntervalCollectionPositionProperty"];
  timeIntervalCollectionProperty: typeof Cesium["TimeIntervalCollectionProperty"];
  timeStandard: typeof Cesium["TimeStandard"];
  timeline: typeof Cesium["Timeline"];
  timelineHighlightRange: typeof Cesium["TimelineHighlightRange"];
  timelineTrack: typeof Cesium["TimelineTrack"];
  tipsify: typeof Cesium["Tipsify"];
  toggleButtonViewModel: typeof Cesium["ToggleButtonViewModel"];
  tonemapper: typeof Cesium["Tonemapper"];
  transforms: typeof Cesium["Transforms"];
  translationRotationScale: typeof Cesium["TranslationRotationScale"];
  tridiagonalSystemSolver: typeof Cesium["TridiagonalSystemSolver"];
  trustedServers: typeof Cesium["TrustedServers"];
  tween: typeof Cesium["Tween"];
  tweenCollection: typeof Cesium["TweenCollection"];
  uniformState: typeof Cesium["UniformState"];
  uri: typeof Cesium["Uri"];
  urlTemplateImageryProvider: typeof Cesium["UrlTemplateImageryProvider"];
  version: typeof Cesium["VERSION"];
  vrButton: typeof Cesium["VRButton"];
  vrButtonViewModel: typeof Cesium["VRButtonViewModel"];
  vrTheWorldTerrainProvider: typeof Cesium["VRTheWorldTerrainProvider"];
  vector3DTileBatch: typeof Cesium["Vector3DTileBatch"];
  vector3DTileContent: typeof Cesium["Vector3DTileContent"];
  vector3DTileGeometry: typeof Cesium["Vector3DTileGeometry"];
  vector3DTilePoints: typeof Cesium["Vector3DTilePoints"];
  vector3DTilePolygons: typeof Cesium["Vector3DTilePolygons"];
  vector3DTilePolylines: typeof Cesium["Vector3DTilePolylines"];
  vector3DTilePrimitive: typeof Cesium["Vector3DTilePrimitive"];
  velocityOrientationProperty: typeof Cesium["VelocityOrientationProperty"];
  velocityVectorProperty: typeof Cesium["VelocityVectorProperty"];
  vertexArray: typeof Cesium["VertexArray"];
  vertexArrayFacade: typeof Cesium["VertexArrayFacade"];
  vertexFormat: typeof Cesium["VertexFormat"];
  verticalOrigin: typeof Cesium["VerticalOrigin"];
  videoSynchronizer: typeof Cesium["VideoSynchronizer"];
  view: typeof Cesium["View"];
  viewer: typeof Cesium["Viewer"];
  viewportQuad: typeof Cesium["ViewportQuad"];
  visibility: typeof Cesium["Visibility"];
  visualizer: typeof Cesium["Visualizer"];
  wallGeometry: typeof Cesium["WallGeometry"];
  wallGeometryLibrary: typeof Cesium["WallGeometryLibrary"];
  wallGeometryUpdater: typeof Cesium["WallGeometryUpdater"];
  wallGraphics: typeof Cesium["WallGraphics"];
  wallOutlineGeometry: typeof Cesium["WallOutlineGeometry"];
  webGlConstants: typeof Cesium["WebGLConstants"];
  webMapServiceImageryProvider: typeof Cesium["WebMapServiceImageryProvider"];
  webMapTileServiceImageryProvider: typeof Cesium["WebMapTileServiceImageryProvider"];
  webMercatorProjection: typeof Cesium["WebMercatorProjection"];
  webMercatorTilingScheme: typeof Cesium["WebMercatorTilingScheme"];
  weightSpline: typeof Cesium["WeightSpline"];
  windingOrder: typeof Cesium["WindingOrder"];
};